# Generated by Django 5.2.8 on 2025-11-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importeTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estadoCesta', models.CharField(choices=[('Activa', 'Activa'), ('Finalizada', 'Finalizada')], default='Activa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('codigoPostal', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Información de Entrega',
                'verbose_name_plural': 'Información de Entregas',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('Tarjeta', 'Tarjeta'), ('Contrareembolso', 'Contrareembolso')], max_length=20)),
                ('estadoPago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado')], default='Pendiente', max_length=15)),
                ('fechaPago', models.DateTimeField(auto_now_add=True)),
                ('iTransaccion', models.CharField(blank=True, help_text='ID de la transacción devuelto por el proveedor de pagos (ej: Stripe).', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Pago del Pedido',
                'verbose_name_plural': 'Pagos de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPedido', models.DateTimeField(auto_now_add=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('EnPreparacion', 'En Preparación'), ('EnEnvio', 'En Envío'), ('Entregado', 'Entregado')], default='Pendiente', max_length=15)),
                ('tipoEntrega', models.CharField(choices=[('Domicilio', 'Domicilio'), ('PuntoRecogida', 'Punto Recogida')], max_length=20)),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('apellidos_cliente', models.CharField(max_length=150)),
                ('email_cliente', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Pedido de Cliente',
                'verbose_name_plural': 'Pedidos de Clientes',
            },
        ),
        migrations.CreateModel(
            name='PuntoRecogida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('codigoPostal', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Punto de Recogida de Pedido',
                'verbose_name_plural': 'Puntos de Recogida de Pedidos',
            },
        ),
    ]
