# Generated by Django 5.2.8 on 2025-11-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cesta', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesta',
            name='productos',
            field=models.ManyToManyField(related_name='cestas', through='productos.ProductoCesta', to='productos.producto'),
        ),
    ]
