# Generated by Django 5.2.8 on 2025-11-15 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cesta', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cesta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cestaDeCompra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cesta_asociada',
            field=models.OneToOneField(help_text='Cesta Finalizada que originó este pedido.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cesta.cesta'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='dirEntrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_domicilio', to='cesta.entrega'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cesta.pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='puntoRecogida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_recogida', to='cesta.puntorecogida'),
        ),
    ]
