# Generated by Django 4.2.25 on 2025-11-16 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('cesta', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='puntoRecogida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_recogida', to='usuarios.puntorecogidapref'),
        ),
    ]
