# Generated by Django 4.2.25 on 2025-11-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0004_alter_pedido_puntorecogida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('TAR', 'Tarjeta'), ('CRD', 'Contrareembolso')], max_length=20),
        ),
    ]
