# Generated by Django 4.2.25 on 2025-11-21 23:25

import cesta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0005_alter_pago_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='public_id',
            field=models.CharField(default=cesta.models.generar_public_id, editable=False, max_length=50, unique=True),
        ),
    ]
