# Generated by Django 4.2.25 on 2025-11-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_nombre_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocesta',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
    ]